title: Prathuasha K B
# logo: /assets/img/headshot_circle.png
#description: text below image

description: M.Sc. Data Science @ TUDâ€™27</br>Aspiring Data Scientist | Focused on ML, Analytics & AI 
github_username: PrathuashaKB
# email: prathuasharao2017@gmail.com
theme: jekyll-theme-minimal
logo: assets/img/pkb.jpg

sidebar:
  - name: Email
    icon: fa-regular fa-envelope
    link: prathuasharao2017@gmail.com
  # - name: CV
  #   icon: fa-regular fa-file-pdf
  #   link: /assets/docs/cv.pdf
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/PrathuashaKB
  - name: LinkedIn
    icon: fa-brands fa-linkedin-in
    link: https://www.linkedin.com/in/prathuasha-k-b-2k2/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
